### ISSUE TITLE
Make timezone configurable

### ISSUE THREAD

**Issue by hmpf** [Uninett/zinolib#46]
Internally, everything happens in UTC. In the frontend, whether using UTC or local time should be configurable.

Since each howitz request makes its own connection to zino with zinolib we could have timezone as a parameter when setting up the manager, and store datetimes accordingly.

See also Uninett/Howitz#61

**Comment by lunkwill42** [comment]
IRL discussion concludes that this is not a necessary feature of zinolib.  As long as all returned timestamps are timezone-aware (i.e. UTC), it's up to the client to convert to another timezone if so desired.
